package com.example.savehaven.utils

/**
 * Educational content provider for SaveHaven's financial literacy features
 * Contains curated financial tips designed for young adults (16-22 years old)
 */
object FinancialTipsProvider {
    val tips = listOf(
        "Track your expenses daily to spot waste.",
        "Set up automatic transfers to your savings.",
        "Review subscriptions monthly and cancel unused ones.",
        "Build an emergency fund covering 3–6 months of expenses.",
        "Pay off high-interest debt first.",
        "Create a realistic monthly budget and stick to it.",
        "Use cash instead of cards to limit spending.",
        "Shop with a list to avoid impulse buys.",
        "Check your credit report annually for errors.",
        "Negotiate bills and ask for discounts.",
        "Save your spare change in a jar.",
        "Plan meals to reduce food waste and save money.",
        "Limit eating out; cook more at home.",
        "Use cashback and rewards credit cards wisely.",
        "Invest early to take advantage of compound interest.",
        "Automate bill payments to avoid late fees.",
        "Set specific financial goals with deadlines.",
        "Keep an eye on your net worth regularly.",
        "Learn the difference between good and bad debt.",
        "Prioritize saving for retirement starting now.",
        "Keep an affordable car or consider public transport.",
        "Buy quality items that last longer.",
        "Avoid lifestyle inflation when your income rises.",
        "Use price comparison tools before big purchases.",
        "Limit credit card use to what you can pay monthly.",
        "Track your financial progress weekly.",
        "Use separate accounts for savings and spending.",
        "Plan for taxes to avoid surprises.",
        "Save windfalls like bonuses instead of spending them.",
        "Set up a sinking fund for irregular expenses.",
        "Avoid payday loans and high-interest quick loans.",
        "Use budgeting apps to stay organized.",
        "Understand your employer’s retirement benefits.",
        "Invest in yourself with skills that boost earning.",
        "Review your insurance policies yearly.",
        "Keep your financial documents organized.",
        "Practice mindful spending by asking “Do I really need this?”",
        "Start a side hustle for extra income.",
        "Pay more than the minimum on credit cards.",
        "Don’t lend money you can’t afford to lose.",
        "Keep an emergency cash stash at home.",
        "Save a fixed percentage of every paycheck.",
        "Read personal finance books or blogs regularly.",
        "Join a local financial education workshop or group.",
        "Use rewards programs to maximize discounts.",
        "Don’t buy on credit without a repayment plan.",
        "Be wary of “too good to be true” financial offers.",
        "Reevaluate your financial goals every 6 months.",
        "Track your subscriptions and recurring payments.",
        "Keep your credit utilization below 30%.",
        "Use tax-advantaged accounts like IRAs or HSAs.",
        "Invest in index funds for diversified exposure.",
        "Keep a spending journal for one month.",
        "Plan large purchases around sales events.",
        "Ask for a raise if you deserve one.",
        "Set up automatic savings for vacations or holidays.",
        "Keep a budget category for fun to avoid burnout.",
        "Buy used or refurbished items when appropriate.",
        "Use energy-efficient appliances to save on bills.",
        "Consider a financial advisor for complex planning.",
        "Limit impulse shopping triggers like online shopping apps.",
        "Pay yourself first before spending on wants.",
        "Take advantage of employer matching contributions.",
        "Use library resources instead of buying books.",
        "Set reminders for bill due dates.",
        "Try the 24-hour rule before making big purchases.",
        "Separate wants from needs in your spending.",
        "Use a cash envelope system for discretionary spending.",
        "Reduce recurring charges like premium TV packages.",
        "Check for errors in your bank and credit card statements.",
        "Start investing with small amounts regularly.",
        "Make extra payments on mortgages to reduce interest.",
        "Take advantage of student discounts and benefits.",
        "Bundle insurance policies for discounts.",
        "Have a financial backup plan for job loss.",
        "Use generic brands instead of name brands.",
        "Review and update your will and estate plans.",
        "Track your spending by category for better insight.",
        "Buy seasonal produce to save on groceries.",
        "Use budgeting challenges to motivate saving.",
        "Turn off unused subscriptions or memberships.",
        "Keep a financial calendar for important deadlines.",
        "Plan for kids’ education costs early.",
        "Sell unused items for extra cash.",
        "Use travel rewards credit cards wisely.",
        "Avoid co-signing loans whenever possible.",
        "Prepare meals at home to save money and eat healthier.",
        "Check your credit score regularly.",
        "Consider refinancing loans to lower rates.",
        "Set short-term and long-term financial goals.",
        "Don’t invest based on emotions or hype.",
        "Learn the basics of investing and finance.",
        "Have multiple income streams for security.",
        "Don’t ignore small savings — they add up over time.",
        "Automate debt repayments where possible.",
        "Track your spending habits monthly and adjust.",
        "Consider low-cost index funds for investing.",
        "Use budgeting apps with notifications and reports.",
        "Save money by carpooling or using public transport.",
        "Don’t keep all your money in one investment type.",
        "Set financial boundaries with friends and family.",
        "Ask for professional advice for complex tax situations.",
        "Review your financial progress at year-end.",
        "Prioritize paying off small debts for quick wins."
    )


    fun getRandomTip(): String {
        return tips.random()
    }
}
